#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {D:/programs/Neuromophic_FPGA/sources/Neuromorphic_Lattice/impl_1}]} {
  file mkdir {D:/programs/Neuromophic_FPGA/sources/Neuromorphic_Lattice/impl_1}
}
cd {D:/programs/Neuromophic_FPGA/sources/Neuromorphic_Lattice/impl_1}

sys_set_attribute -gui on -msg {D:/programs/Neuromophic_FPGA/sources/Neuromorphic_Lattice/promote.xml}
msg_load {D:/programs/Neuromophic_FPGA/sources/Neuromorphic_Lattice/promote.xml}
des_set_project_udb -in {Neuromorphic_Lattice_impl_1_syn.udb} -out {Neuromorphic_Lattice_impl_1_map.udb} -milestone map -pm je5d00
des_set_reference_udb -clean
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false vio false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
